name:                hid3-and-seq
version:             0.1.0.0
github:              "josiah14-MachineLearning/ID3-and-Derivatives/haskell/sequential/hid3-and-seq"
license:             AGPL-3.0
author:              "Josiah Berkebile"
maintainer:          "hw3ynh4j9jw3@opayq.com"
copyright:           "2019 Cloyd Garrett (Josiah) Berkebile"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            "Naive sequential implementation of the ID3 algorithm"
category:            "Machine Learning: Decision Trees"

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/josiah14-MachineLearning/ID3-and-Derivatives#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.1 && < 2
- optional-args < 2
- hspec >= 2.0 && < 3
- QuickCheck >= 2.0 && < 3
- hoogle
- Frames >= 0.3
- foldl
- vinyl
- pipes
- microlens
- text
- Unique >= 0.4.7

library:
  source-dirs:
    src

executables:
  hid3-and-seq-exe:
    main:
      Main.hs
    source-dirs:
      app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hid3-and-seq
    - ghcid
    - hoogle

tests:
  hid3-and-seq-test:
    main:
      Spec.hs
    source-dirs:
      spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hid3-and-seq
    - hspec >= 2.0 && < 3
    - QuickCheck >= 2.0 && < 3
